# Generated by Django 3.1.3 on 2020-11-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201126_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_id',
            new_name='stripe_pid',
        ),
    ]
