# Generated by Django 3.1.2 on 2020-11-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colors',
            new_name='color',
        ),
    ]
