# Generated by Django 3.1.3 on 2020-11-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201103_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grape_variety',
            options={'verbose_name_plural': 'Grape Varieties'},
        ),
    ]
