# Generated by Django 3.1.3 on 2020-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201106_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_listed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
