# Generated by Django 3.1.3 on 2020-11-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201129_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
