# Generated by Django 3.1.3 on 2020-12-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201201_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='grape_variety',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='friendly_name',
        ),
    ]
